In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("canada_per_capita_income.csv")
df.head()

year  per capita income (US$)
0  1970              3399.299037
1  1971              3768.297935
2  1972              4251.175484
3  1973              4804.463248
4  1974              5576.514583

In [6]:
model = linear_model.LinearRegression()
model.fit(df.drop('per capita income (US$)',axis="columns"),df.drop('year',axis="columns"))

LinearRegression()

model.predict([[1970]])

In [7]:
model.predict([[1970]])

C:\Users\asus\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[-134.55966672]])

In [8]:
model.coef_

array([[828.46507522]])

In [9]:
model.intercept_

array([-1632210.75785546])

In [10]:
import pickle


In [11]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [14]:
from sklearn import joblib

ImportError: cannot import name 'joblib' from 'sklearn' (C:\Users\asus\anaconda3\lib\site-packages\sklearn\__init__.py)

In [15]:
joblib.dump(model, 'model_joblib')


NameError: name 'joblib' is not defined

In [ ]:
mj = joblib.load('model_joblib')
mj.coef_
mj.intercept_
mj.predict([[5000]])
